s2i-core: "https://github.com/sclorg/s2i-base-container.git"
postgresql: "https://github.com/sclorg/postgresql-container.git"
redis: "https://github.com/sclorg/redis-container.git"
s2i-base: "https://github.com/sclorg/s2i-base-container.git"
mongodb: "https://github.com/sclorg/mongodb-container.git"
mariadb: "https://github.com/sclorg/mariadb-container.git"
httpd: "https://github.com/sclorg/httpd-container.git"
nginx: "https://github.com/sclorg/nginx-container.git"
python3: "https://github.com/sclorg/s2i-python-container.git"
