#!/usr/bin/env python3

# description     : Script for helping with the rebuild of container images.
# author          : pkubat@redhat.com
# notes           : Rewritten from a shell script originally created by hhorak@redhat.com.
# python_version  : 3.x

import sys

from container_workflow_tool.cli import Cli
from container_workflow_tool.main import RebuilderError

if __name__ == "__main__":
    try:
        cli = Cli(sys.argv[1:])
        cli.run()
    except RebuilderError as e:
        print("ERROR: {}".format(e))
        sys.exit(1)
