#!/usr/bin/env python3

# description     : Script for helping with the rebuild of container images.
# author          : pkubat@redhat.com
# notes           : Rewritten from a shell script originally created by hhorak@redhat.com.
# python_version  : 3.x

from container_workflow_tool.cli import run as run_cwt


if __name__ == "__main__":
    run_cwt()
