FROM registry.fedoraproject.org/fedora:34

RUN dnf install -y ansible

COPY image-requirements/* /image-requirements/
RUN ansible-playbook -v -c local -i localhost, image-requirements/install-requirements.yaml

RUN git config --global user.email "foo@bar.com"
RUN git config --global user.name "foobar"

WORKDIR /cwt

COPY ./ /cwt
RUN pip3 install --user --no-cache-dir -r tests/test-requirements.txt
RUN pip3 install .
CMD make tests
